version: '2'
services:
#    db:
#        image: mysql
#        volumes:
#            - "./.data/db:/var/lib/mysql"
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_DATABASE: project
#            MYSQL_USER: root
#            MYSQL_PASSWORD: root

    symfony:
        build: .

        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        networks:
            - mynet
            
    apache2:
        build: ./docker/apache2
        ports:
            - "8080:80"
        volumes_from:
            - symfony
        networks:
            - mynet

networks:
    mynet:
        driver: bridge